### ISSUE TITLE
As an air quality expert, I would like that the testing activities related to the connection between MQTT algorab server and A22 AQ DC for the retrieval of the innovative AQ sensors of the A22 are completed

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#127]
The application (data collector) is not working as expected. I tried to fix it and did it in part, but I noted a lot of issues which are still causing data not being delivered.
- [x] data linearization causes infinite values which are not handled at all and therefore not sending any of the computed data
- [x] buffer which contains fetched data is being delete on every push data call even before the data is send
- [x] data is not being buffered, if pushData hasn't returned yet
- [x] values like temperature are completely out of range (probably beacause of lineraization functions, needs to be checked)
- [x] max data ques can be 1000 which causes lots of history data loss 
- [x] not all stations are being created, which provide data
- [x] writer is trying to cascade station on persist
... there is surely more to come but still a lot to fix

**Comment by bertolla** [comment]
Waiting for Nicola P. to implement a way of not stopping all other applications deployment.

**Comment by bertolla** [comment]
This is log output when trying to deploy the war file:
```
10-Oct-2019 01:00:37.787 INFO [localhost-startStop-1] org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions Loading XML bean definitions from URL [file:/var/lib/tomcat8/webapps/dc-algorab-a22/WEB-INF/classes/META-INF/spring/applicationContext.xml]
10-Oct-2019 01:00:38.178 INFO [localhost-startStop-1] org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition Overriding bean definition for bean 'jobScheduler' with a different definition: replacing [Generic bean: class [it.bz.idm.bdp.augeg4.JobScheduler]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [/var/lib/tomcat8/webapps/dc-algorab-a22/WEB-INF/classes/it/bz/idm/bdp/augeg4/JobScheduler.class]] with [Generic bean: class [it.bz.idm.bdp.augeg4.JobScheduler]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in URL [file:/var/lib/tomcat8/webapps/dc-algorab-a22/WEB-INF/classes/META-INF/spring/applicationContext.xml]]
2019-10-10 01:00:39,467 [localhost-startStop-1] INFO  it.bz.idm.bdp.augeg4.JobScheduler - mqtt push pass:testMQTT
2019-10-10 01:00:39,476 [localhost-startStop-1] INFO  it.bz.idm.bdp.augeg4.JobScheduler - mqtt push user:testMQTT
2019-10-10 01:00:39,476 [localhost-startStop-1] INFO  it.bz.idm.bdp.augeg4.JobScheduler - mqtt push client:airQuinoLinearization
2019-10-10 01:00:39,476 [localhost-startStop-1] INFO  it.bz.idm.bdp.augeg4.JobScheduler - mqtt push port:61619
2019-10-10 01:00:39,476 [localhost-startStop-1] INFO  it.bz.idm.bdp.augeg4.JobScheduler - mqtt push topic:AirQuino/LinearizedData
2019-10-10 01:00:39,476 [localhost-startStop-1] INFO  it.bz.idm.bdp.augeg4.JobScheduler - mqtt push uri:tcp://mqtt-test.algorab.net
2019-10-10 01:00:39,480 [localhost-startStop-1] DEBUG it.bz.idm.bdp.augeg4.util.AugeMqttClient - MQTT client with:tcp://mqtt-test.algorab.net:61619 airQuinoLinearization AirQuino/LinearizedData
2019-10-10 01:00:39,520 [localhost-startStop-1] DEBUG it.bz.idm.bdp.augeg4.util.AugeMqttClient - connect...:
2019-10-10 01:00:39,520 [localhost-startStop-1] DEBUG it.bz.idm.bdp.augeg4.util.AugeMqttClient - Connection with:testMQTT testMQTT
2019-10-10 01:00:39,813 [localhost-startStop-1] INFO  it.bz.idm.bdp.augeg4.JobScheduler - onDeploy() called
2019-10-10 01:00:39,813 [localhost-startStop-1] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - loadPreviouslySyncedStations() called
```

**Comment by rcavaliere** [comment]
@bertolla can we change strategy and dedicate a separate environment for this DC which implements a MQTT broker?

**Comment by bertolla** [comment]
A separate environment could work to avoid the deployment issue, but I do not understand why we need a MQTT broker. To be independent from a22 test environment?

**Comment by rcavaliere** [comment]
That's what algorab can provide us. As you know we have also to provide back to them some elaborations on the raw data. If this has not huge impacts for us, I would recommend to go in that direction

**Comment by bertolla** [comment]
Deployed the datacollector on a seperate test server and it run but it seems to me that the mqtt server is no longer reachable
```
MQTT client with:tcp://mqtt-test.algorab.net:61619 airQuinoLinearization AirQuino/LinearizedData
2019-11-07 15:14:42,627 [localhost-startStop-1] DEBUG it.bz.idm.bdp.augeg4.util.AugeMqttClient - connect...:
2019-11-07 15:14:42,631 [localhost-startStop-1] DEBUG it.bz.idm.bdp.augeg4.util.AugeMqttClient - Connection with:testMQTT testMQTT
Unable to connect to server (32103) - java.net.ConnectException: Connection refused (Connection refused)

```

**Comment by bertolla** [comment]
Now it's running again and inserting data. Pleas check if everything works fine.

**Comment by rcavaliere** [comment]
@bertolla before I complete the testing, I would like to ask you to deploy on the testing environment a new version of the DC that Nicola should have committed. It contains new elaboration logic. When done, please put in testing again and assign the issue to me. Thanks!

**Comment by bertolla** [comment]
The last version from Nicola was already deployed on 10th december after we took his pull request.

**Comment by rcavaliere** [comment]
@bertolla did you stop the data collector on the testing environment? I can't see the AQ stations... also the folder with the code of Nicola is missing from the repository. Can you please check?

**Comment by rcavaliere** [comment]
@bertolla I have made some enhancements to the DC of Nicola. Can you please check why the DC is now not storing any data in the DB anymore? Eventually we can immediately test the DC with the production environment. We just need to change these configurations: src/main/resources/META-INF/spring/application.properties

**Comment by rcavaliere** [comment]
@bertolla can you please provide me the static IP addresses with which we will call the data provider? Like the Municipality of BZ, A22 will set a rule so to allow requests to their end-point only from this IP address. Does the IP address change from testing to production environment? In case please give me both.

**Comment by bertolla** [comment]
> @bertolla I have made some enhancements to the DC of Nicola. Can you please check why the DC is now not storing any data in the DB anymore? Eventually we can immediately test the DC with the production environment. We just need to change these configurations: src/main/resources/META-INF/spring/application.properties

After making the changes have you also deployed the application? If not, than you changes won't affect the dc

**Comment by rcavaliere** [comment]
Just made a commit in the current development branch, isn't this enough?

**Comment by bertolla** [comment]
Hi Roberto, your changes make the thests fail. See https://jenkins.testingmachine.eu/job/it.bz.opendatahub.bigdataplatform/job/data-collectors/job/environment-a22.test-archive/

**Comment by rcavaliere** [comment]
Can we check this in the short meeting I have proposed to you tomorrow, also to discuss the bike sharing stuff?

**Comment by rcavaliere** [comment]
@bertolla the DC seems to works fine now. There are some calculations that do not work as expected, I take the task to review the elaboration engine in the code.

**Comment by rcavaliere** [comment]
@bertolla I think that the elaborations still do not work properly. Can we sit together and debug a little bit this component? I will make a proposal of meeting

**Comment by rcavaliere** [comment]
Waiting for A22 production end-point to complete testing activities (we need real data...)

**Comment by rcavaliere** [comment]
Important big news. Door was open. The IP address to be called is http://213.21.183.12:61616
@bertolla can you adapt the data collector, so we can check if all works?

**Comment by bertolla** [comment]
@rcavaliere I put it on production but it does not work
```
2020-02-26 07:20:00,014 [Scheduler-4] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - syncStations() called
2020-02-26 07:21:00,004 [Scheduler-4] INFO  it.bz.idm.bdp.augeg4.JobScheduler - pushStations() called
2020-02-26 07:21:00,004 [Scheduler-4] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - loadPreviouslySyncedStations() called
2020-02-26 07:21:00,015 [Scheduler-4] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - syncStations() called
2020-02-26 07:22:00,000 [Scheduler-4] INFO  it.bz.idm.bdp.augeg4.JobScheduler - pushStations() called
2020-02-26 07:22:00,000 [Scheduler-4] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - loadPreviouslySyncedStations() called
2020-02-26 07:22:00,011 [Scheduler-4] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - syncStations() called
2020-02-26 07:23:00,000 [Scheduler-4] INFO  it.bz.idm.bdp.augeg4.JobScheduler - pushStations() called
2020-02-26 07:23:00,000 [Scheduler-4] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - loadPreviouslySyncedStations() called
2020-02-26 07:23:00,011 [Scheduler-4] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - syncStations() called
2020-02-26 07:24:00,000 [Scheduler-4] INFO  it.bz.idm.bdp.augeg4.JobScheduler - pushStations() called
2020-02-26 07:24:00,001 [Scheduler-4] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - loadPreviouslySyncedStations() called
2020-02-26 07:24:00,013 [Scheduler-4] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - syncStations() called
2020-02-26 07:25:00,000 [Scheduler-1] INFO  it.bz.idm.bdp.augeg4.JobScheduler - pushDataTypes() called.
2020-02-26 07:25:00,000 [Scheduler-1] INFO  it.bz.idm.bdp.augeg4.DataTypeDelegate - syncDataTypes() called.
2020-02-26 07:25:00,000 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.JobScheduler - pushStations() called
2020-02-26 07:25:00,000 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - loadPreviouslySyncedStations() called
2020-02-26 07:25:00,011 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - syncStations() called
2020-02-26 07:26:00,000 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.JobScheduler - pushStations() called
2020-02-26 07:26:00,000 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - loadPreviouslySyncedStations() called
2020-02-26 07:26:00,011 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - syncStations() called
2020-02-26 07:27:00,000 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.JobScheduler - pushStations() called
2020-02-26 07:27:00,000 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - loadPreviouslySyncedStations() called
2020-02-26 07:27:00,011 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - syncStations() called
2020-02-26 07:28:00,000 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.JobScheduler - pushStations() called
2020-02-26 07:28:00,000 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - loadPreviouslySyncedStations() called
2020-02-26 07:28:00,013 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - syncStations() called
2020-02-26 07:29:00,000 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.JobScheduler - pushStations() called
2020-02-26 07:29:00,000 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - loadPreviouslySyncedStations() called
2020-02-26 07:29:00,012 [Scheduler-8] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - syncStations() called
2020-02-26 07:30:00,000 [Scheduler-10] INFO  it.bz.idm.bdp.augeg4.JobScheduler - pushDataTypes() called.
2020-02-26 07:30:00,000 [Scheduler-10] INFO  it.bz.idm.bdp.augeg4.DataTypeDelegate - syncDataTypes() called.
2020-02-26 07:30:00,001 [Scheduler-5] INFO  it.bz.idm.bdp.augeg4.JobScheduler - pushStations() called
2020-02-26 07:30:00,001 [Scheduler-5] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - loadPreviouslySyncedStations() called
2020-02-26 07:30:00,031 [Scheduler-5] INFO  it.bz.idm.bdp.augeg4.StationsDelegate - syncStations() called
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:189)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:136)
	... 1 more
2020-02-26 07:30:01,802 [Scheduler-9] WARN  it.bz.idm.bdp.augeg4.DataDelegate - fetchData() elaboratedData.isEmpty()
2020-02-26 07:30:01,802 [Scheduler-9] INFO  it.bz.idm.bdp.augeg4.DataDelegate - pushDataToAuge() called.
2020-02-26 07:30:01,802 [Scheduler-9] INFO  it.bz.idm.bdp.augeg4.DataDelegate - dequeueProcessedDataToAuge() called.
2020-02-26 07:30:01,802 [Scheduler-9] WARN  it.bz.idm.bdp.augeg4.DataDelegate - pushDataToAuge() data.isEmpty()
2020-02-26 07:30:01,802 [Scheduler-9] INFO  it.bz.idm.bdp.augeg4.DataDelegate - pushDataToHub() called.
2020-02-26 07:30:01,802 [Scheduler-9] INFO  it.bz.idm.bdp.augeg4.DataDelegate - dequeueProcessedDataToHub() called.
2020-02-26 07:30:01,802 [Scheduler-9] WARN  it.bz.idm.bdp.augeg4.DataDelegate - pushDataToHub() data.isEmpty()
```

**Comment by rcavaliere** [comment]
@bertolla can you please debug it a little bit?

**Comment by bertolla** [comment]
From the logging I would say that the mqtt client fails when trying to read the data stream but to understand more I would need to know about the codebase. It's like finding a needle in a Haystack.
Furthermore we can only access from the one server ip, which means to debug I would need to setup vpn and so on.

**Comment by rcavaliere** [comment]
so, how you suggest to proceed? I would avoid to involve Nicola...

**Comment by bertolla** [comment]
We either find somebody else who can handle this(like chris) or invest in it our time. Not really in my interest :unamused:, since I barley know anything about mqtt and kinda lost trust in the endpoints.

**Comment by rcavaliere** [comment]
@bertolla thanks for the feedback, please consider the following:

- we are expected to put this in component in production in **days**, not weeks / or months. Giving this task to other third parties is not suitable in this case;

- now we have the production end-point. This means that now we have something stable to work with; before we had to work with something that was in most cases down and delivering little and fake data.

I would therefore beg you if you can take some time to investigate the problem. I am pretty confident that we can manage this in short time. I don't expect that the issue is related to the MQTT protocol.

**Comment by bertolla** [comment]
Sure, but don't forget. If I start debugging this problem on the production environment all data we consume will not be available anymore on the mwtt server so it will be lost. If the system works in the test environment and not in the production environement it mean something got changed in the prod env which our client can't handle.

**Comment by rcavaliere** [comment]
Yes sure, this is something that we have to pay to complete the work. But such data are available for offline analysis, so don't care about this.

**Comment by bertolla** [comment]
By checking online I found this:
> My issue resulted from the clientId being the same for the publisher/subscriber. Was getting errors with Persistence datastore already being in use as well.
https://stackoverflow.com/questions/19813101/java-io-eofexception-with-paho

It's our case. I can try change the id but I don't know if server side they also need to do any changes

**Comment by bertolla** [comment]
@rcavaliere  As you can see in the issue it says that this problem can have multiple reasons for giving the error message and some are client related but some also server related. In any case the server is closing the socket after a certain time. I'm trying the client related issues right now but with no success till now.

One thing which I noticed, which can also be a big factor. I the document the endpoint refers to the endpoint protocol as `http`, while in the test environment `tcp` was used and also the client only supports `tcp` and `ssl`. Is this an error in the document or is this what we got from a22?

**Comment by rcavaliere** [comment]
OK, let's ask algorab for some clarifications, it could be that they have the queue full of data and this could be the reason for this connection problem.

**Comment by bertolla** [comment]
I tried to install a command line mqtt client on the server and connect to the given endpoint. Even there I get `Timeout while waiting for CONNACK`, which confirms what happens in the datacollector. Is the information that we have in that document all we got or is there more information available?

**Comment by rcavaliere** [comment]
@bertolla please check this with algorab. Nicola Pedot can be contacted if needed.

**Comment by bertolla** [comment]
I tried to understand for a while now and finally reached a conclusion. While I deleted db for bluetoothelaboration usecase this dc was still running and inserting data in the db and it caused a conflict in station and types. Going to fix this now and it should be ready for testing.

**Comment by bertolla** [comment]
@rcavaliere 
After trying several things I noticed a few things that do not fit:
- shouldn't it be in real time? It seems like it's 2 hours behind. Does the mqtt sever provide time values in utc or local time?
- is the mqtt server providing values in chronological order or just random?
- is it ok if I do push data every minute instead of every 5 minutes or is it going to afflict elaborations?

**Comment by rcavaliere** [comment]
@bertolla:
Data should be in UTC time. What is the current convention?
For the other two points, let me first ask algorab...

**Comment by bertolla** [comment]
Numberformat Exception on linearization stops complete datapush event

**Comment by bertolla** [comment]
In cases where elaboratedValue is 0 the delinerization of this raw data returns infinite as Value. Since the logic cannot handle infinite values it throws a Numberformat exception and stops all further proecessing. No data is send to writer.
There are 2 things that need to be fixed:
- the linearization function which does not handle 0 values
- how the case should be handled and how processing should be resumed
https://github.com/noi-techpark/bdp-commons/blob/784990121eb9b3b41d1e2e192f2724ef5d77c507/data-collectors/environment-a22/src/main/java/it/bz/idm/bdp/augeg4/fun/delinearize/MeasurementDelinearizer.java#L69

**Comment by bertolla** [comment]
Makes sense since some of this function do a logarithm of numbers. And log 0 is not defined I guess.
I know nothing about this functions and do not wanna change existing logic.
https://github.com/noi-techpark/bdp-commons/blob/784990121eb9b3b41d1e2e192f2724ef5d77c507/data-collectors/environment-a22/src/main/java/it/bz/idm/bdp/augeg4/fun/delinearize/MeasurementDelinearizer.java#L35

**Comment by rcavaliere** [comment]
@bertolla ok, good to hear that this could be the issue. 
First of all, let me explain what the Data Collector should do:

1. - the algorab broker sends the value "y". 
2. - the Data Collector" computes the raw measurement (x = f(y)), that we call "x" through one of different linearization functions (in the API should be identified by the identifier linFuncId)
3. - the Data Collector computes "z" through a complex formula (z = f(x)). This is the elaborated measurement that we need
4. - the Data Collector saves x and z in the ODH Core
5. - the Data Collector returns z to the algorab broker 

The log function is used in point 2 (should be linFuncId=2, correct?). It's correct, log(0) does not exist (is - infinite). In theory we shouldn't get 0 values, but it could be that is a default value e.g. in case no data is there. Can't we just add a logic like follows:
if (value != 0)-> do the calculation
else -> do not the calculation (ignore this vale)
The algorithm should then go to the next value to be computed.

What do you think?

**Comment by bertolla** [comment]
I think there are probably more of such cases and they should be all handled by dc logic.
In this specific case it would be more like **value > 0** if I'm not mistaken.
Each function should not allow undoable math and skip all that values

**Comment by bertolla** [comment]
I still need a rule for this function `Math.exp((y - b) / a)`. Till now I have `a!=0`, but I noticed that if the number between braces is high enough the result is infinite, so this could also be the reason for failure.

**Comment by rcavaliere** [comment]
@bertolla, this is correct, put value > 0 (log(x) with x < 0 is not possible)
The coefficients a, b etc. should not be zero, and be returned by the API. You could also put something like if Math.exp((y - b) / a) is > Threshold (e.g. 10.000) then do not consider valid this computation

**Comment by bertolla** [comment]
OK I fixed this case by not considering values which are null or infinite.
Another thing I noticed in the code that every time push data was called, the buffer containing messages got flushed and close to no data made it past. I think there are even more problems.

**Comment by rcavaliere** [comment]
@bertolla I think that the probably is related to this: we have a lot of stations that do not have any linearization function assigned (and associated coefficients, see screenshots below). This means, the MQTT broker does not even foresee these attributes in the API! I think that the DC is not working fine in this use case. My personal opinion is to fix this also with the support of BrennerLEC projects. Every station and every data type should have something (if no linearization is applied, just put ‘linFuncId=1’, ‘paramA=1’ and ‘paramB=0’ -> this means raw values are passed as they are: y = ax+b becomes y=x)

![image004](https://user-images.githubusercontent.com/9825179/84465915-75c32e00-ac78-11ea-97fc-e1cab49077c8.png)
![image005](https://user-images.githubusercontent.com/9825179/84465916-75c32e00-ac78-11ea-9b4a-a819784e1249.png)
![image006](https://user-images.githubusercontent.com/9825179/84465917-765bc480-ac78-11ea-88b0-5aee9d0cfd5e.png)



![image003](https://user-images.githubusercontent.com/9825179/84465914-74920100-ac78-11ea-93ae-55c5ff1c59ca.png)

**Comment by rcavaliere** [comment]
@bertolla technically the DC is now working as expected. We have some issues with the processed values, but it is not a DC problem but a computation problem that I have to fix with UNITN. Let's close this issue and if we see then further bugs / adaptation needs we will open new user stories.
