### ISSUE TITLE
Bug: the Data Collector Innovative Air Quality Sensors of A22 does not provide real-time data anymore

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#305]
High Priority, Deadline 28 February 2022

**Comment by Piiit** [comment]
@rcavaliere Does it work now?

**Comment by Piiit** [comment]
I think it does not work. I get the following error once a day:

```
02-Nov-2021 12:00:32.096 INFO [http-nio-8080-exec-1] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
        java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x000xdd0x010x000x000xd90x030x03E0xf5:0x91p0x01y0x1d0x0c0x9e0xf70x1b+0x92>0x0f0x1d0xe00xa90xf90x810x1c]. HTTP method names must be tokens
                at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:432)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:502)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1627)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:748)
```

**Comment by Piiit** [comment]
@rcavaliere Could we give this to the original author or must it be resolved internally?

**Comment by rcavaliere** [comment]
@Piiit it does not work. I think this is quite difficult to understand for our data provider what's the issue. Probably we need more debugging on our side...

**Comment by Piiit** [comment]
OK, I thought to ask the developer of the data collector, not the data provider... but maybe it is correct, that we need more details... I would need to understand the whole process behind the collector, does it use a VPN or can I test it locally?

**Comment by rcavaliere** [comment]
@Piiit Patrick B. wrote the data collector. Yes, if I remember well there is also a VPN for the connection to the end-point, please check

**Comment by Piiit** [comment]
@rcavaliere I cannot find any VPN installation, configuration, or documentation anywhere. It is a MQTT connection, but without a VPN I guess, maybe that was only necessary initially, and then it might have been dropped? 

I cannot find any documentation, do you have some pdf or other assets?

**Comment by Piiit** [comment]
@rcavaliere I also tested the mqtt connection, but currently I am not able to subscribe... however, I need to figure out which parameters must be set in detail... also here, no documentation exist, I need to extract that information from the Java code now

**Comment by Piiit** [comment]
Also the testing endpoint in our integration tests is not reachable anymore: `tcp://mqtt-test.algorab.net:61619`

**Comment by rcavaliere** [comment]
@Piiit I have checked this a little bit since it has passed quite a long time here. I think the problem is in the connection with the end-point. For security reasons, at the end A22 decided to **not** have a VPN but to define a rule so that only our IP address 108.128.203.57 was allowed to connect to the end-point (http://213.21.183.12:61616) through the TCP port 80 (http). I fear that they set a rule that the connection was allowed only up to the end of September (end of BrennerLEC project). Can you check if you can ping the end-point from this IP address? If not, I will ask A22 to check.

**Comment by Piiit** [comment]
@rcavaliere Tested with `nc -vz 213.21.183.12 61616`, got a timeout... I think we can no longer connect from 52.212.112.40

**Comment by rcavaliere** [comment]
@Piiit I got a feedback from A22 that they didn't change anything, and that the rules are still active. They also told me that however they didn't receive any attempts to connect from our system in the last 30 days! So probably is there something that does not allow our end-point to connect to the A22 end-point?

**Comment by Piiit** [comment]
@rcavaliere I will check again, do we have a documentation about their endpoint and the full configuration of what we used? I cannot find anything... If we do not have it, could you please ask them to provide one?

**Comment by Piiit** [comment]
@rcavaliere I tried again with nmap, but nothing seems open... I think the configuration has changed or we do not know the latest configuration agreed upon with Patrick... could that be?

Tested several ports in the range:  61600-61699 and 1800-1900

**Comment by rcavaliere** [comment]
@Piiit are you testing from the production environment where the Data Collector is hosted? A22 put a rule on the IP address (see above), nothing more. Could it be that we changed our IP address? That could be simply the reason...

**Comment by rcavaliere** [comment]
Status: waiting for A22 to reconfigure the access rules based on the new IP addresses we provided

**Comment by rcavaliere** [comment]
@Piiit A22 should have found and solved the problem. Can you please check from the new IP addresses if you can connect to the back-end system?

**Comment by Piiit** [comment]
@rcavaliere It seems to be open, I will redeploy the DC to be sure...

**Comment by Piiit** [comment]
It works, please check our testing database, if the data is correct.

I see that some security issues exist though, the log contains sensible data, we need to fix them...

Is it safe to be run on our staging environment and also on production at the same time? I see, that some result get written back... does the retrieving endpoint handle duplicates?

The external test server is not reachable anymore, maybe we need another integration test setup here...

**Comment by rcavaliere** [comment]
@Piiit are you sure that we are receiving new data? I checked the DB, but I don't see up-to-date data. By the way, you are right. The DC provides back elaborated measurements. With Patrick B. we had to work directly in the production environment, even if not optimal. Also in this case if you think that now the connection works try to reactivate the Data Collector in the production environment and let's if we get new data...

**Comment by Piiit** [comment]
I checked the DB, but we do not have fresh data their... something is still not working. I also see old data from 2020, but with a DC that has a newer version as the current one, that is really strange.

**Comment by Piiit** [comment]
> By the way, you are right. The DC provides back elaborated measurements. With Patrick B. we had to work directly in the production environment, even if not optimal. Also in this case if you think that now the connection works try to reactivate the Data Collector in the production environment and let's if we get new data...

I will add a flag to deactivate the push to their MQTT endpoint, so that we can still test the rest of the service. 

In addition, I need to deactivate deprecated integration tests, and remove the debug output of credentials.

**Comment by rcavaliere** [comment]
@Piiit can you try to restart the DC in production? Probably all these issues are because as said the testing environment was not aligned with the broker of A22

**Comment by Piiit** [comment]
The problem is that the old production pipeline is not compatible with our new servers, I need to refactor that first...

**Comment by rcavaliere** [comment]
Ok, but probably this is the best way to proceed. I am afraid that if we disable the return channel to the A22 broker, we create some issues for them

**Comment by Piiit** [comment]
@rcavaliere I wrote the production pipeline, fixed our writer and deployed the DC on production, but the MQTT endpoint seems to be unreachable again... it worked today, but now all ports are closed again. Tested from all IPs that I gave you...

**Comment by rcavaliere** [comment]
@Piiit thanks for the update, just wrote back to A22 again. In case next week I put you directly in contact with the technician here which is trying to solve this issue

**Comment by sseppi** [comment]
@rcavaliere is this issue still present or the data flow has been riactivated?

**Comment by rcavaliere** [comment]
@sseppi no more relevant, closing
